name: tests
on:
  push:
  #   branches: ['main']
  #   paths-ignore:
  #     - "docs/*"
  # pull_request:
  #   paths-ignore:
  #     - "docs/*"
jobs:
  test:
    strategy:
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout code
      uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
    - name: Install Go
      uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7
      with:
        go-version: '1.22'
        cache: true
    - name: Test
      run: go test -covermode atomic ./...
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      with:
        limit-access-to-actor: true